// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBebTX3WQA-8nKP84dVo8zOUq6Zbtv100w',
    appId: '1:834534025096:ios:153d4456cf41887c9cbc3d',
    messagingSenderId: '834534025096',
    projectId: 'aisaiah-event-hub',
    storageBucket: 'aisaiah-event-hub.firebasestorage.app',
    iosBundleId: 'com.eventhub.eventHub',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEcxBJLcsLKPtduEMwjvbqJJP15BbslZw',
    appId: '1:834534025096:web:0b066610aafd7bca9cbc3d',
    messagingSenderId: '834534025096',
    projectId: 'aisaiah-event-hub',
    authDomain: 'aisaiah-event-hub.firebaseapp.com',
    storageBucket: 'aisaiah-event-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH-B9E5xK4FM2pIrL0QZPciDWdFVOqwnU',
    appId: '1:834534025096:android:4ea3068e837ec6fa9cbc3d',
    messagingSenderId: '834534025096',
    projectId: 'aisaiah-event-hub',
    storageBucket: 'aisaiah-event-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBebTX3WQA-8nKP84dVo8zOUq6Zbtv100w',
    appId: '1:834534025096:ios:153d4456cf41887c9cbc3d',
    messagingSenderId: '834534025096',
    projectId: 'aisaiah-event-hub',
    storageBucket: 'aisaiah-event-hub.firebasestorage.app',
    iosBundleId: 'com.eventhub.eventHub',
  );
}
